# site properties and page defaults
title: Michael J O“\u0027”Neill
subtitle: Assistant Professor
description: I am an Assistant Professor in the Statistics and Operations Research Department at the University of North Carolina at Chapel Hill. My research interests lie in the design, analysis and implementation of continuous, nonlinear optimization methods.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: mikeoneill@unc.edu
  google-scholar: 0ipTvMcAAAAJ
  github: MichaelJONeill

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
