- title: A Line-Search Descent Algorithm for Strict Saddle Functions with Complexity Guarantees
  authors:
    - "[Michael J. O'Neill]"
    - "[Stephen J. Wright]"
  publisher: Journal of Machine Learning Research
  date: 2023-01-01
  link: https://jmlr.org/papers/v24/20-608.html
